### ISSUE TITLE
panic during monitoring of processes

### ISSUE THREAD

**Issue by deepakprabhakara** [DataDog/datadog-process-agent#268] opened 2019-03-17 01:33 UTC
We have a list of processes that we monitor, I unfortunately do not know which process causes the following panic but the stack trace should have enough hints to fix this panic:-

datdog-agent version: 6.10.1
Running on kubernetes as a daemonset.

```Mar 16 11:38:22 dg1 k8s_datadog-agent_datadog-agent-:  [NETWORK] network-tracer exited with code 0, disabling
Mar 16 11:38:23 dg1 k8s_datadog-agent_datadog-agent-:  [ TRACE ] trace-agent exited with code 0, disabling
Mar 17 01:01:25 dg4 k8s_datadog-agent_datadog-agent-:  [PROCESS] panic: runtime error: invalid memory address or nil pointer dereference
Mar 17 01:01:25 dg4 k8s_datadog-agent_datadog-agent-:  [PROCESS] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x121fdd3]
Mar 17 01:01:25 dg4 k8s_datadog-agent_datadog-agent-:  [PROCESS]
Mar 17 01:01:25 dg4 k8s_datadog-agent_datadog-agent-:  [PROCESS] goroutine 173 [running]:
Mar 17 01:01:25 dg4 k8s_datadog-agent_datadog-agent-:  [PROCESS] github.com/DataDog/datadog-process-agent/checks.fmtProcesses(0xc4204ce700, 0xc4207bb3e0, 0xc4204f0ae0, 0xc42020f180, 0x0, 0x4d, 0x15ae947, 0x9, 0x415a3ff170a3d70a, 0x416b01d26199999a, ...)
Mar 17 01:01:25 dg4 k8s_datadog-agent_datadog-agent-:  [PROCESS] 	/home/jenkins/workspace/process-agent-build-ddagent/go/src/github.com/DataDog/datadog-process-agent/checks/process.go:215 +0x5d3
Mar 17 01:01:25 dg4 k8s_datadog-agent_datadog-agent-:  [PROCESS] github.com/DataDog/datadog-process-agent/checks.(*ProcessCheck).Run(0x2276820, 0xc4204ce700, 0x32665ce4, 0x0, 0x0, 0x0, 0x0, 0x0)
Mar 17 01:01:25 dg4 k8s_datadog-agent_datadog-agent-:  [PROCESS] 	/home/jenkins/workspace/process-agent-build-ddagent/go/src/github.com/DataDog/datadog-process-agent/checks/process.go:83 +0x275
Mar 17 01:01:25 dg4 k8s_datadog-agent_datadog-agent-:  [PROCESS] main.(*Collector).runCheck(0xc4202ce140, 0x16fe8e0, 0x2276820)
Mar 17 01:01:25 dg4 k8s_datadog-agent_datadog-agent-:  [PROCESS] 	/home/jenkins/workspace/process-agent-build-ddagent/go/src/github.com/DataDog/datadog-process-agent/cmd/agent/collector.go:85 +0x203
Mar 17 01:01:25 dg4 k8s_datadog-agent_datadog-agent-:  [PROCESS] main.(*Collector).run.func2(0xc4202ce140, 0xc4200f65a0, 0x16fe8e0, 0x2276820)
Mar 17 01:01:25 dg4 k8s_datadog-agent_datadog-agent-:  [PROCESS] 	/home/jenkins/workspace/process-agent-build-ddagent/go/src/github.com/DataDog/datadog-process-agent/cmd/agent/collector.go:151 +0x322
Mar 17 01:01:25 dg4 k8s_datadog-agent_datadog-agent-:  [PROCESS] created by main.(*Collector).run
Mar 17 01:01:25 dg4 k8s_datadog-agent_datadog-agent-:  [PROCESS] 	/home/jenkins/workspace/process-agent-build-ddagent/go/src/github.com/DataDog/datadog-process-agent/cmd/agent/collector.go:139 +0x3f4
Mar 17 01:01:25 dg4 k8s_datadog-agent_datadog-agent-:  [PROCESS] process-agent exited with code 2, signal 0, restarting in 2 seconds
```

**Comment by sunhay** [comment] 2019-03-26 15:41
Sorry for the delay! Taking a look at this now

**Comment by deepakprabhakara** [comment] 2019-03-26 17:33
@sunhay Thank you, much appreciated!

**Comment by deepakprabhakara** [comment] 2019-04-02 14:28
@sunhay any updates on this? This issue is plaguing us on production.

**Comment by sunhay** [comment] 2019-04-02 14:41
@deepakprabhakara This looks like the first case we've seen with this particular panic. I can try to see if we can prioritize a fix. 

Can you provide system details that you're seeing this on? Specifically I'm interested in the: OS + Kernel version where you're seeing these issues.

**Comment by deepakprabhakara** [comment] 2019-04-02 19:30
@sunhay Interesting, here are the details of the system:-
OS is CentOS 7.4.1708, kernel version is 4.16.4-1.el7.elrepo.x86_64.
datadog-agent v6.10.1 is running as a docker container (official) orchestrated via Kubernetes.

**Comment by deepakprabhakara** [comment] 2019-04-04 14:02
@sunhay Forgot to add that it's a Kubernetes DaemonSet with hostNetwork and hostPID.

**Comment by sunhay** [comment] 2019-04-04 14:24
Thanks for the details @deepakprabhakara - I'll share with the team and see if we can find out exactly why this is happening

**Comment by leeavital** [comment] 2019-04-05 14:05
Hi @deepakprabhakara,  it looks like this issue is being caused by `procfs` (which the process agent uses to source process information) is partly inaccessible.  We we've been unable to pin down exactly what about your environment is causing the issue, but we've made [a change](https://github.com/DataDog/datadog-process-agent/pull/286) that should make the errors not-fatal. Instead of panic-ing, you'll see processes with certain metrics zeroed out in datadog. This will land in the next version of the datadog-agent.  


To get to the bottom of why some of your process data is inaccessible, I recommend enabling debug logging on the process agent.  That will log every time a file in `procfs` is inaccessible, which will help us know which processes/files are causing the problem.

**Comment by deepakprabhakara** [comment] 2019-04-08 15:11
@leeavital Thanks, I'll let you know when I have updated and the logs reveal more.

**Comment by irabinovitch** [comment] 2019-10-22 03:00
Hi @deepakprabhakara , Were you by any chance able to find  logs once you updated? Should we close this issue and open a support ticket in its place?

**Comment by deepakprabhakara** [comment] 2019-10-31 16:36
@irabinovitch This can be closed, I haven't seen this panic in the newer versions.

**Closed** 2019-10-31 17:27 UTC
